[programs.devnet]
solanaexploration = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/obedt/.config/solana/id.json"

[scripts]
test = "node tests/solanaexploration.js"
